# coding: utf-8

REASON_CODES = {
    -1: 'INDEFINIDO',
    0: 'SUCESSO NA TRANSAÇÃO',
    1: 'PAGAMENTO - O CARTÃO NÃO TEM FUNÇÃO CRÉDITO',
    2: 'PAGAMENTO - O PAGAMENTO NÃO FOI AUTORIZADO',
    3: 'PAGAMENTO - PROBLEMAS DE COMUNICAÇÃO COM A ADQUIRENTE'
}
